import { Lead } from "./types";

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();
}

export function seedLeads(): Lead[] {
  return [
    {
      id: "seed-nova",
      createdAt: daysAgo(6),
      updatedAt: daysAgo(1),
      contactName: "Sarah Chen",
      contactTitle: "VP of Revenue Operations",
      email: "sarah.chen@novapay.io",
      linkedin: "linkedin.com/in/sarahchen",
      company: "NovaPay",
      website: "novapay.io",
      industry: "Fintech / Payments",
      companySize: "180 employees",
      location: "London, UK",
      fundingStage: "Series B ($40M, 4 months ago)",
      techStack: ["Salesforce", "Outreach", "Snowflake"],
      buyingSignals: [
        "Hiring 6 SDRs this quarter",
        "New VP of Sales started last month",
        "Recently expanded to EU market",
      ],
      notes:
        "Downloaded our pipeline benchmarks report. RevOps team of 4, growing fast after Series B.",
      fitScore: 88,
      intentScore: 74,
      priorityScore: 84,
      estimatedDealSize: "$48,000 ARR",
      closeProbability: 45,
      status: "engaged",
      crm: {
        leadStatus: "engaged",
        nextAction: "Follow up on pricing question, propose 30-min demo",
        followUpDate: daysAgo(-2),
        conversationSummary:
          "Replied to first email asking about integration with Salesforce and pricing tiers. Positive tone, mentioned Q3 planning.",
        painPoints: [
          "SDR ramp time too long (4+ months)",
          "No visibility into outbound conversion by segment",
        ],
        goals: ["Scale outbound to EU without doubling headcount"],
        decisionMakers: ["Sarah Chen (VP RevOps)", "Tom Wilkes (VP Sales, new)"],
        timeline: "Evaluating tools for Q3 kickoff",
        competitors: ["Clari", "Gong"],
        notes: "Prefers email over calls. GDPR compliance is a hard requirement.",
      },
      activity: [
        {
          id: "a1",
          timestamp: daysAgo(6),
          type: "note",
          summary: "Lead created from content download",
        },
        {
          id: "a2",
          timestamp: daysAgo(4),
          type: "agent_run",
          summary: "Initial qualification run — priority 84, personalized email sent",
        },
        {
          id: "a3",
          timestamp: daysAgo(1),
          type: "objection",
          summary: "Asked about pricing and Salesforce integration",
        },
      ],
    },
    {
      id: "seed-forge",
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
      contactName: "Marcus Reid",
      contactTitle: "Head of Growth",
      email: "marcus@forgemetrics.com",
      linkedin: "linkedin.com/in/marcusreid",
      company: "Forge Metrics",
      website: "forgemetrics.com",
      industry: "B2B SaaS / Analytics",
      companySize: "45 employees",
      location: "Austin, TX",
      fundingStage: "Seed ($6M)",
      techStack: ["HubSpot", "Apollo"],
      buyingSignals: ["Posted about outbound struggles on LinkedIn last week"],
      notes: "Small but growing team. Founder-led sales transitioning to first sales hires.",
      fitScore: null,
      intentScore: null,
      priorityScore: null,
      estimatedDealSize: null,
      closeProbability: null,
      status: "new",
      crm: {
        leadStatus: "new",
        nextAction: "Research and qualify",
        followUpDate: null,
        conversationSummary: "",
        painPoints: [],
        goals: [],
        decisionMakers: [],
        timeline: "",
        competitors: [],
        notes: "",
      },
      activity: [
        {
          id: "b1",
          timestamp: daysAgo(3),
          type: "note",
          summary: "Lead created from LinkedIn signal",
        },
      ],
    },
    {
      id: "seed-atlas",
      createdAt: daysAgo(14),
      updatedAt: daysAgo(2),
      contactName: "Priya Nair",
      contactTitle: "Chief Operating Officer",
      email: "priya.nair@atlaslogistics.co",
      linkedin: "linkedin.com/in/priyanair",
      company: "Atlas Logistics",
      website: "atlaslogistics.co",
      industry: "Logistics / Supply Chain",
      companySize: "600 employees",
      location: "Rotterdam, NL",
      fundingStage: "Private equity backed",
      techStack: ["Microsoft Dynamics", "SAP"],
      buyingSignals: ["Announced digital transformation initiative in press release"],
      notes:
        "Enterprise deal. Long sales cycle expected. COO owns the transformation budget.",
      fitScore: 71,
      intentScore: 38,
      priorityScore: 52,
      estimatedDealSize: "$120,000 ARR",
      closeProbability: 15,
      status: "nurturing",
      crm: {
        leadStatus: "nurturing",
        nextAction: "Share logistics case study, wait 3 weeks",
        followUpDate: daysAgo(-18),
        conversationSummary:
          "Polite reply: interested but transformation program starts next fiscal year. Asked to reconnect in Q4.",
        painPoints: ["Manual quoting process", "Fragmented data across 3 systems"],
        goals: ["Reduce operational cost 12% by next year"],
        decisionMakers: ["Priya Nair (COO)", "IT Director (unknown name)"],
        timeline: "Q4 this year at earliest",
        competitors: ["Internal build"],
        notes: "Do not push. Nurture with relevant content only.",
      },
      activity: [
        {
          id: "c1",
          timestamp: daysAgo(14),
          type: "note",
          summary: "Lead created from press release signal",
        },
        {
          id: "c2",
          timestamp: daysAgo(10),
          type: "agent_run",
          summary: "Qualification run — good fit, low urgency, moved to nurture",
        },
        {
          id: "c3",
          timestamp: daysAgo(2),
          type: "status_change",
          summary: "Status set to nurturing, follow-up scheduled",
        },
      ],
    },
  ];
}
